# Build with:
#    docker build -t colibris/ci-builder -f Dockerfile.ci-builder .

FROM docker:latest

RUN apk add --no-cache py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make git curl && \
    pip install docker-compose

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
